-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 18:07:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Autosalon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Autosalon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Autosalon` DEFAULT CHARACTER SET utf8 ;
USE `Autosalon` ;

-- -----------------------------------------------------
-- Table `Autosalon`.`garancija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`garancija` (
  `idGarancija` INT NOT NULL AUTO_INCREMENT,
  `godina` INT NOT NULL,
  PRIMARY KEY (`idGarancija`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`proizvodjac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`proizvodjac` (
  `idProizvodjac` INT NOT NULL AUTO_INCREMENT,
  `nazivProizvodjaca` VARCHAR(45) NOT NULL,
  `idGarancija` INT NOT NULL,
  PRIMARY KEY (`idProizvodjac`),
  INDEX `fk_proizvodjac_garancija_idx` (`idGarancija` ASC) VISIBLE,
  CONSTRAINT `fk_proizvodjac_garancija`
    FOREIGN KEY (`idGarancija`)
    REFERENCES `Autosalon`.`garancija` (`idGarancija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`model` (
  `idModel` INT NOT NULL AUTO_INCREMENT,
  `idProizvodjac` INT NOT NULL,
  `nazivModela` VARCHAR(45) NOT NULL,
  `cijenaModela` DECIMAL NOT NULL,
  PRIMARY KEY (`idModel`),
  INDEX `fk_model_proizvodjac1_idx` (`idProizvodjac` ASC) VISIBLE,
  CONSTRAINT `fk_model_proizvodjac1`
    FOREIGN KEY (`idProizvodjac`)
    REFERENCES `Autosalon`.`proizvodjac` (`idProizvodjac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`oprema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`oprema` (
  `idOprema` INT NOT NULL AUTO_INCREMENT,
  `nivoOpreme` VARCHAR(45) NOT NULL,
  `opis` TEXT(200) NOT NULL,
  `procenat` DECIMAL(2,2) NOT NULL,
  PRIMARY KEY (`idOprema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`motor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`motor` (
  `idMotor` INT NOT NULL AUTO_INCREMENT,
  `tipMotora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMotor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`bojaAuta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`bojaAuta` (
  `idBojaAuta` INT NOT NULL AUTO_INCREMENT,
  `bojaAuta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBojaAuta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`tip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`tip` (
  `idTip` INT NOT NULL AUTO_INCREMENT,
  `tipAutomobila` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTip`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`automobil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`automobil` (
  `idAutomobil` INT NOT NULL AUTO_INCREMENT,
  `idModel` INT NOT NULL,
  `idTip` INT NOT NULL,
  `idMotor` INT NOT NULL,
  `idOprema` INT NOT NULL,
  `idBojaAuta` INT NOT NULL,
  `cijenaAutomobila` DECIMAL NOT NULL,
  PRIMARY KEY (`idAutomobil`),
  INDEX `fk_automobil_oprema1_idx` (`idOprema` ASC) VISIBLE,
  INDEX `fk_automobil_motor1_idx` (`idMotor` ASC) VISIBLE,
  INDEX `fk_automobil_model1_idx` (`idModel` ASC) VISIBLE,
  INDEX `fk_automobil_bojaAuta1_idx` (`idBojaAuta` ASC) VISIBLE,
  INDEX `fk_automobil_tip1_idx` (`idTip` ASC) VISIBLE,
  CONSTRAINT `fk_automobil_oprema1`
    FOREIGN KEY (`idOprema`)
    REFERENCES `Autosalon`.`oprema` (`idOprema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_automobil_motor1`
    FOREIGN KEY (`idMotor`)
    REFERENCES `Autosalon`.`motor` (`idMotor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_automobil_model1`
    FOREIGN KEY (`idModel`)
    REFERENCES `Autosalon`.`model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_automobil_bojaAuta1`
    FOREIGN KEY (`idBojaAuta`)
    REFERENCES `Autosalon`.`bojaAuta` (`idBojaAuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_automobil_tip1`
    FOREIGN KEY (`idTip`)
    REFERENCES `Autosalon`.`tip` (`idTip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`kupac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`kupac` (
  `idKupac` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `brojTelefona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKupac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`adresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`adresa` (
  `idAdresa` INT NOT NULL AUTO_INCREMENT,
  `nazivUlice` VARCHAR(45) NOT NULL,
  `brojUlice` VARCHAR(45) NOT NULL,
  `nazivGrada` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`osiguranje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`osiguranje` (
  `idOsiguranje` INT NOT NULL AUTO_INCREMENT,
  `nazivOsiguranja` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOsiguranje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`salon` (
  `idSalon` INT NOT NULL AUTO_INCREMENT,
  `nazivSalona` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  `idAdresa` INT NOT NULL,
  `idOsiguranje` INT NOT NULL,
  PRIMARY KEY (`idSalon`),
  INDEX `fk_salon_adresa1_idx` (`idAdresa` ASC) VISIBLE,
  INDEX `fk_salon_osiguranje1_idx` (`idOsiguranje` ASC) VISIBLE,
  CONSTRAINT `fk_salon_adresa1`
    FOREIGN KEY (`idAdresa`)
    REFERENCES `Autosalon`.`adresa` (`idAdresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_salon_osiguranje1`
    FOREIGN KEY (`idOsiguranje`)
    REFERENCES `Autosalon`.`osiguranje` (`idOsiguranje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`telefon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`telefon` (
  `idtelefon` INT NOT NULL AUTO_INCREMENT,
  `brojTelefona` VARCHAR(45) NOT NULL,
  `idSalon` INT NOT NULL,
  PRIMARY KEY (`idtelefon`),
  INDEX `fk_telefon_salon1_idx` (`idSalon` ASC) VISIBLE,
  CONSTRAINT `fk_telefon_salon1`
    FOREIGN KEY (`idSalon`)
    REFERENCES `Autosalon`.`salon` (`idSalon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`prodavac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`prodavac` (
  `idProdavac` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProdavac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`nacinPlacanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`nacinPlacanja` (
  `idNacinPlacanja` INT NOT NULL AUTO_INCREMENT,
  `nacinPlacanja` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNacinPlacanja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`narudzba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`narudzba` (
  `idNarudzba` INT NOT NULL AUTO_INCREMENT,
  `idAutomobil` INT NOT NULL,
  `idKupac` INT NOT NULL,
  `idSalon` INT NOT NULL,
  `idProdavac` INT NOT NULL,
  `idNacinPlacanja` INT NOT NULL,
  `datumNarudzbe` DATE NOT NULL,
  `datumDolaska` DATE NOT NULL,
  `cijena` DECIMAL NOT NULL,
  PRIMARY KEY (`idNarudzba`),
  INDEX `fk_narudzba_kupac1_idx` (`idKupac` ASC) VISIBLE,
  INDEX `fk_narudzba_automobil1_idx` (`idAutomobil` ASC) VISIBLE,
  INDEX `fk_narudzba_salon1_idx` (`idSalon` ASC) VISIBLE,
  INDEX `fk_narudzba_prodavac1_idx` (`idProdavac` ASC) VISIBLE,
  INDEX `fk_narudzba_nacinPlacanja1_idx` (`idNacinPlacanja` ASC) VISIBLE,
  CONSTRAINT `fk_narudzba_kupac1`
    FOREIGN KEY (`idKupac`)
    REFERENCES `Autosalon`.`kupac` (`idKupac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_narudzba_automobil1`
    FOREIGN KEY (`idAutomobil`)
    REFERENCES `Autosalon`.`automobil` (`idAutomobil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_narudzba_salon1`
    FOREIGN KEY (`idSalon`)
    REFERENCES `Autosalon`.`salon` (`idSalon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_narudzba_prodavac1`
    FOREIGN KEY (`idProdavac`)
    REFERENCES `Autosalon`.`prodavac` (`idProdavac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_narudzba_nacinPlacanja1`
    FOREIGN KEY (`idNacinPlacanja`)
    REFERENCES `Autosalon`.`nacinPlacanja` (`idNacinPlacanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`racun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`racun` (
  `idRacun` INT NOT NULL AUTO_INCREMENT,
  `idNarudzba` INT NOT NULL,
  `datumPreuzimanja` DATE NOT NULL,
  PRIMARY KEY (`idRacun`),
  INDEX `fk_racun_narudzba1_idx` (`idNarudzba` ASC) VISIBLE,
  CONSTRAINT `fk_racun_narudzba1`
    FOREIGN KEY (`idNarudzba`)
    REFERENCES `Autosalon`.`narudzba` (`idNarudzba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`registracija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`registracija` (
  `idRegistracija` INT NOT NULL AUTO_INCREMENT,
  `registacijskaOznaka` VARCHAR(45) NOT NULL,
  `datumRegistacije` DATE NOT NULL,
  `datumIstekaRegistracije` DATE NOT NULL,
  `idOsiguranje` INT NOT NULL,
  `idNarudzba` INT NOT NULL,
  PRIMARY KEY (`idRegistracija`),
  INDEX `fk_registracija_osiguranje1_idx` (`idOsiguranje` ASC) VISIBLE,
  INDEX `fk_registracija_narudzba1_idx` (`idNarudzba` ASC) VISIBLE,
  CONSTRAINT `fk_registracija_osiguranje1`
    FOREIGN KEY (`idOsiguranje`)
    REFERENCES `Autosalon`.`osiguranje` (`idOsiguranje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registracija_narudzba1`
    FOREIGN KEY (`idNarudzba`)
    REFERENCES `Autosalon`.`narudzba` (`idNarudzba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`tipoviModela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`tipoviModela` (
  `idModel` INT NOT NULL,
  `idTip` INT NOT NULL,
  PRIMARY KEY (`idModel`, `idTip`),
  INDEX `fk_model_has_tip_tip1_idx` (`idTip` ASC) VISIBLE,
  INDEX `fk_model_has_tip_model1_idx` (`idModel` ASC) VISIBLE,
  CONSTRAINT `fk_model_has_tip_model1`
    FOREIGN KEY (`idModel`)
    REFERENCES `Autosalon`.`model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_model_has_tip_tip1`
    FOREIGN KEY (`idTip`)
    REFERENCES `Autosalon`.`tip` (`idTip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autosalon`.`motoriModela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autosalon`.`motoriModela` (
  `idModel` INT NOT NULL,
  `idMotor` INT NOT NULL,
  PRIMARY KEY (`idModel`, `idMotor`),
  INDEX `fk_model_has_motor_motor1_idx` (`idMotor` ASC) VISIBLE,
  INDEX `fk_model_has_motor_model1_idx` (`idModel` ASC) VISIBLE,
  CONSTRAINT `fk_model_has_motor_model1`
    FOREIGN KEY (`idModel`)
    REFERENCES `Autosalon`.`model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_model_has_motor_motor1`
    FOREIGN KEY (`idMotor`)
    REFERENCES `Autosalon`.`motor` (`idMotor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
